import math

import pandas as pd

from scoutgraph.features.player_matrix import PLAYER_ID_COLUMNS
from scoutgraph.storage.paths import ProjectPaths


PLAYER_FEATURE_MATRIX_PATH = "statsbomb/player_features.parquet"
SIMILARITY_ID_COLUMNS = PLAYER_ID_COLUMNS


def find_similar_players(
    paths: ProjectPaths,
    *,
    player: str,
    limit: int = 5,
) -> pd.DataFrame:
    """Find players with the most similar normalized feature profiles."""
    matrix = load_player_feature_matrix(paths)
    target_index = _find_player_index(matrix, player)
    metric_columns = _numeric_metric_columns(matrix)
    vectors = _standardize(matrix[metric_columns])
    target_vector = vectors.loc[target_index]

    similarities = vectors.apply(lambda row: _cosine_similarity(target_vector, row), axis=1)
    results = matrix.loc[:, SIMILARITY_ID_COLUMNS].copy()
    results["similarity"] = similarities.round(3)
    results = results.drop(index=target_index)

    return results.sort_values(
        ["similarity", "player_name"],
        ascending=[False, True],
    ).head(limit).reset_index(drop=True)


def load_player_feature_matrix(paths: ProjectPaths) -> pd.DataFrame:
    """Load the combined player feature matrix generated by the features command."""
    matrix_path = paths.processed_data / PLAYER_FEATURE_MATRIX_PATH
    if not matrix_path.exists():
        msg = (
            "Player feature matrix not found. "
            "Run `scoutgraph features player-matrix` before similarity commands."
        )
        raise FileNotFoundError(msg)
    return pd.read_parquet(matrix_path)


def format_similar_players(players: pd.DataFrame, *, limit: int = 5) -> list[str]:
    lines = []
    for _, row in players.head(limit).iterrows():
        lines.append(
            f"{row['player_name']} | {row['team_name']} | "
            f"similarity {row['similarity']:.3f}"
        )
    return lines


def _find_player_index(matrix: pd.DataFrame, player: str) -> int:
    matches = matrix["player_name"].str.contains(player, case=False, na=False)
    if not matches.any():
        msg = f"No player found matching {player!r}."
        raise ValueError(msg)
    return int(matrix[matches].index[0])


def _numeric_metric_columns(matrix: pd.DataFrame) -> list[str]:
    numeric_columns = matrix.select_dtypes(include="number").columns.tolist()
    return [column for column in numeric_columns if column not in {"player_id", "team_id"}]


def _standardize(metrics: pd.DataFrame) -> pd.DataFrame:
    std = metrics.std(ddof=0).replace(0, 1)
    return (metrics - metrics.mean()) / std


def _cosine_similarity(left: pd.Series, right: pd.Series) -> float:
    left_norm = math.sqrt(float((left * left).sum()))
    right_norm = math.sqrt(float((right * right).sum()))
    if left_norm == 0 or right_norm == 0:
        return 0.0
    return float((left * right).sum() / (left_norm * right_norm))
