import math

import pandas as pd

from scoutgraph.features.player_matrix import PLAYER_ID_COLUMNS
from scoutgraph.similarity.explanations import (
    SimilarityExplanation,
    explain_player_similarity,
    format_similarity_explanation,
)
from scoutgraph.similarity.player_positions import load_player_position_groups
from scoutgraph.storage.paths import ProjectPaths


PLAYER_FEATURE_MATRIX_PATH = "statsbomb/player_features.parquet"
SIMILARITY_ID_COLUMNS = PLAYER_ID_COLUMNS
RATE_METRIC_COLUMNS = {
    "pass_completion_pct",
    "avg_pass_length",
    "avg_carry_distance",
    "avg_shot_distance",
}


def find_similar_players(
    paths: ProjectPaths,
    *,
    player: str,
    limit: int = 5,
    same_position: bool = False,
) -> pd.DataFrame:
    """Find players with the most similar normalized feature profiles."""
    matrix = load_player_feature_matrix(paths)
    if same_position:
        matrix = _filter_same_position_group(matrix, paths=paths, player=player)
    target_index = _find_player_index(matrix, player)
    metric_columns = _numeric_metric_columns(matrix)
    vectors = _standardize(matrix[metric_columns])
    target_vector = vectors.loc[target_index]

    similarities = vectors.apply(lambda row: _cosine_similarity(target_vector, row), axis=1)
    results = matrix.loc[:, SIMILARITY_ID_COLUMNS].copy()
    results["similarity"] = similarities.round(3)
    results = results.drop(index=target_index)

    return results.sort_values(
        ["similarity", "player_name"],
        ascending=[False, True],
    ).head(limit).reset_index(drop=True)


def load_player_feature_matrix(paths: ProjectPaths) -> pd.DataFrame:
    """Load the combined player feature matrix generated by the features command."""
    matrix_path = paths.processed_data / PLAYER_FEATURE_MATRIX_PATH
    if not matrix_path.exists():
        msg = (
            "Player feature matrix not found. "
            "Run `scoutgraph features player-matrix` before similarity commands."
        )
        raise FileNotFoundError(msg)
    return pd.read_parquet(matrix_path)


def format_similar_players(players: pd.DataFrame, *, limit: int = 5) -> list[str]:
    return format_similar_players_with_explanations(players, limit=limit)


def explain_similar_players(
    paths: ProjectPaths,
    *,
    player: str,
    players: pd.DataFrame,
) -> dict[str, SimilarityExplanation]:
    """Explain each returned similar player against the selected player."""
    matrix = load_player_feature_matrix(paths)
    return {
        str(row["player_name"]): explain_player_similarity(
            matrix,
            player=player,
            compared_player=str(row["player_name"]),
        )
        for _, row in players.iterrows()
    }


def format_similar_players_with_explanations(
    players: pd.DataFrame,
    *,
    limit: int = 5,
    explanations: dict[str, SimilarityExplanation] | None = None,
) -> list[str]:
    lines = []
    for _, row in players.head(limit).iterrows():
        player_name = str(row["player_name"])
        lines.append(
            f"{player_name} | {row['team_name']} | "
            f"similarity {row['similarity']:.3f}"
        )
        if explanations is None:
            continue
        lines.extend(format_similarity_explanation(explanations[player_name]))
    return lines


def _find_player_index(matrix: pd.DataFrame, player: str) -> int:
    matches = matrix["player_name"].str.contains(player, case=False, na=False)
    if not matches.any():
        msg = f"No player found matching {player!r}."
        raise ValueError(msg)
    return int(matrix[matches].index[0])


def _numeric_metric_columns(matrix: pd.DataFrame) -> list[str]:
    numeric_columns = matrix.select_dtypes(include="number").columns.tolist()
    return [
        column
        for column in numeric_columns
        if column.endswith("_per_90") or column in RATE_METRIC_COLUMNS
    ]


def _filter_same_position_group(
    matrix: pd.DataFrame,
    *,
    paths: ProjectPaths,
    player: str,
) -> pd.DataFrame:
    position_groups = load_player_position_groups(paths)
    matrix = matrix.merge(position_groups, on=["player_id", "team_id"], how="left")
    target_index = _find_player_index(matrix, player)
    target_position_group = matrix.loc[target_index, "position_group"]
    if pd.isna(target_position_group):
        msg = f"No position group found for player matching {player!r}."
        raise ValueError(msg)
    return matrix[matrix["position_group"] == target_position_group].reset_index(drop=True)


def _standardize(metrics: pd.DataFrame) -> pd.DataFrame:
    std = metrics.std(ddof=0).replace(0, 1)
    return (metrics - metrics.mean()) / std


def _cosine_similarity(left: pd.Series, right: pd.Series) -> float:
    left_norm = math.sqrt(float((left * left).sum()))
    right_norm = math.sqrt(float((right * right).sum()))
    if left_norm == 0 or right_norm == 0:
        return 0.0
    return float((left * right).sum() / (left_norm * right_norm))
